# Generated by Django 6.0.7 on 2026-07-29 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='produit',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom',
            field=models.CharField(default='Produit inconnu', max_length=200),
        ),
        migrations.AddField(
            model_name='produit',
            name='nutriscore',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=1),
        ),
        migrations.CreateModel(
            name='Remplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements_originaux', to='search.produit')),
                ('produit_remplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements_proposes', to='search.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
