# Generated by Django 6.0.7 on 2026-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_produit_ingredient_produit_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
