# Generated by Django 6.0.7 on 2026-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_produit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
