# Generated by Django 6.0.7 on 2026-08-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_produit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
