# Generated by Django 6.0.7 on 2026-08-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_produit_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='brand',
            new_name='brands',
        ),
    ]
