# Generated by Django 6.0.7 on 2026-08-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_rename_brand_produit_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='brands',
            new_name='marque',
        ),
    ]
